receivers:
  otlp:
    protocols:
      grpc:
  filelog:
    include: [ /var/log/*.log ]

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

exporters:
  prometheus:
    namespace: test-space
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true
    endpoint: "0.0.0.0:8889"
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, spanmetrics]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]