global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'open_telemetry:8889' ]

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'otel-python-demo'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'sender:8000' ]
  - job_name: 'nats-server'
    static_configs:
      - targets: [ 'prometheus-nats-exporter:7777' ]

  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'jaeger:14269' ]


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

