{
 "title": "Panini microservice",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "app",
    "query": "label_values(panini_listen_latency_seconds_bucket, app_name)"
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(panini_listen_latency_seconds_bucket, server)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(panini_listen_total{app_name=~\"^$app_name$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(panini_listen_total{status=\"success\", app_name=~\"^$app_name$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(panini_listen_total{status=\"failed\", app_name=~\"^$app_name$\"}[1m]))"
    }
   ]
  },
  { "title": "Received messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Msg rate by subject",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(panini_listen_total{app_name=~\"^$app_name$\"}[1m]))by (subject)",
     "legendFormat": "{{subject}}"
    }
   ]
  },
  {
   "title": "Msg rate by status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(panini_listen_total{app_name=~\"^$app_name$\"}[1m])) by (status, app_name)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Msg latency by subject",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(panini_listen_latency_seconds_bucket{app_name=~\"^$app_name$\"}[1m])) by (le, app_name, subject))",
     "legendFormat": "{{subject}}"
    }
   ]
  },
  {
   "title": "Msg latency quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(panini_listen_latency_seconds_bucket{app_name=~\"^$app_name$\"}[5m])) by (le, app_name))",
     "legendFormat": "p=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(panini_listen_latency_seconds_bucket[5m])) by (le, app_name))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(panini_listen_latency_seconds_bucket[5m])) by (le, app_name))",
     "legendFormat": "p=0.90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(panini_listen_latency_seconds_bucket[5m])) by (le, app_name))",
     "legendFormat": "p=0.50"
    }
   ]
  }
 ]
}